import { 
  Contact, Message, MessageThread, CalendarEvent, Task, Project, 
  Document, Folder, Meeting, Notification, AIsuggestion, Connector, 
  Avatar, AppState, TranscriptEntry, MeetingMinutes, FollowUpDraft 
} from './types';

// Helper to create dates relative to today
const today = new Date();
const addDays = (days: number) => new Date(today.getTime() + days * 24 * 60 * 60 * 1000);
const addHours = (hours: number) => new Date(today.getTime() + hours * 60 * 60 * 1000);
const subtractDays = (days: number) => new Date(today.getTime() - days * 24 * 60 * 60 * 1000);
const subtractHours = (hours: number) => new Date(today.getTime() - hours * 60 * 60 * 1000);

// Priority Contacts (CFO scenario)
export const contacts: Contact[] = [
  {
    id: 'c1',
    name: 'Sarah Chen',
    email: 'sarah.chen@boardco.com',
    role: 'Board Chair',
    company: 'BoardCo Holdings',
    isPriority: true,
    avatar: 'SC',
  },
  {
    id: 'c2',
    name: 'Michael Torres',
    email: 'mtorres@kpmg.com',
    role: 'Audit Partner',
    company: 'KPMG',
    isPriority: true,
    avatar: 'MT',
  },
  {
    id: 'c3',
    name: 'David Park',
    email: 'david.park@capitalone.com',
    role: 'Relationship Manager',
    company: 'Capital One',
    isPriority: true,
    avatar: 'DP',
  },
  {
    id: 'c4',
    name: 'Jennifer Walsh',
    email: 'jwalsh@company.com',
    role: 'CEO',
    company: 'Acme Corp',
    isPriority: true,
    avatar: 'JW',
  },
  {
    id: 'c5',
    name: 'Robert Kim',
    email: 'rkim@company.com',
    role: 'Finance Director',
    company: 'Acme Corp',
    isPriority: true,
    avatar: 'RK',
  },
  {
    id: 'c6',
    name: 'Lisa Anderson',
    email: 'landerson@company.com',
    role: 'Controller',
    company: 'Acme Corp',
    isPriority: false,
    avatar: 'LA',
  },
  {
    id: 'c7',
    name: 'James Wilson',
    email: 'jwilson@company.com',
    role: 'Treasury Manager',
    company: 'Acme Corp',
    isPriority: false,
    avatar: 'JWI',
  },
  {
    id: 'c8',
    name: 'Emily Brown',
    email: 'ebrown@law.com',
    role: 'Legal Counsel',
    company: 'Smith & Associates',
    isPriority: false,
    avatar: 'EB',
  },
  {
    id: 'c9',
    name: 'Alex Thompson',
    email: 'athompson@company.com',
    role: 'FP&A Manager',
    company: 'Acme Corp',
    isPriority: false,
    avatar: 'AT',
  },
  {
    id: 'c10',
    name: 'Maria Garcia',
    email: 'mgarcia@investor.com',
    role: 'Investment Director',
    company: 'Summit Capital',
    isPriority: false,
    avatar: 'MG',
  },
];

// Projects
export const projects: Project[] = [
  {
    id: 'p1',
    name: 'Board Pack',
    description: 'Q4 2024 Board Meeting preparation and materials',
    priority: 'high',
    color: 'rose',
    participants: [contacts[0], contacts[3], contacts[4]],
    createdAt: subtractDays(30),
  },
  {
    id: 'p2',
    name: 'Audit 2026',
    description: 'Annual audit coordination with KPMG',
    priority: 'high',
    color: 'lavender',
    participants: [contacts[1], contacts[5]],
    createdAt: subtractDays(60),
  },
  {
    id: 'p3',
    name: 'Lender Refinance',
    description: 'Capital One facility refinancing',
    priority: 'high',
    color: 'sky',
    participants: [contacts[2], contacts[6]],
    createdAt: subtractDays(45),
  },
  {
    id: 'p4',
    name: 'Budget 2026',
    description: 'Annual budget planning and forecasting',
    priority: 'medium',
    color: 'mint',
    participants: [contacts[4], contacts[8]],
    createdAt: subtractDays(14),
  },
];

// Folders
export const folders: Folder[] = [
  { id: 'f1', name: 'Board Pack', projectId: 'p1' },
  { id: 'f2', name: 'Financials', parentId: 'f1', projectId: 'p1' },
  { id: 'f3', name: 'Narrative', parentId: 'f1', projectId: 'p1' },
  { id: 'f4', name: 'Emails', parentId: 'f1', projectId: 'p1' },
  { id: 'f5', name: 'Audit 2026', projectId: 'p2' },
  { id: 'f6', name: 'Requests', parentId: 'f5', projectId: 'p2' },
  { id: 'f7', name: 'Responses', parentId: 'f5', projectId: 'p2' },
  { id: 'f8', name: 'Lender Refinance', projectId: 'p3' },
  { id: 'f9', name: 'Forecasts', parentId: 'f8', projectId: 'p3' },
  { id: 'f10', name: 'Term Sheet', parentId: 'f8', projectId: 'p3' },
  { id: 'f11', name: 'Budget 2026', projectId: 'p4' },
];

// Documents
export const documents: Document[] = [
  {
    id: 'd1',
    title: 'Q4 Financial Summary',
    type: 'xlsx',
    folderId: 'f2',
    projectId: 'p1',
    lastUpdated: subtractDays(2),
    size: '2.4 MB',
    preview: 'Consolidated financial statements showing Q4 revenue of $142M, up 12% YoY. EBITDA margin improved to 18.3%.',
    tags: ['financials', 'Q4', 'board'],
    linkedContacts: ['c1', 'c4', 'c5'],
  },
  {
    id: 'd2',
    title: 'CEO Strategic Update',
    type: 'pptx',
    folderId: 'f3',
    projectId: 'p1',
    lastUpdated: subtractDays(1),
    size: '8.1 MB',
    preview: 'Strategic initiatives update: Digital transformation on track, M&A pipeline active with 3 targets in due diligence.',
    tags: ['strategy', 'board', 'executive'],
    linkedContacts: ['c1', 'c4'],
  },
  {
    id: 'd3',
    title: 'Board Deck Draft v3',
    type: 'pptx',
    folderId: 'f1',
    projectId: 'p1',
    lastUpdated: today,
    size: '15.2 MB',
    preview: 'Complete board presentation including financials, operations, risk update, and 2026 outlook.',
    tags: ['board', 'presentation', 'draft'],
    linkedContacts: ['c1'],
  },
  {
    id: 'd4',
    title: 'Audit PBC List',
    type: 'xlsx',
    folderId: 'f6',
    projectId: 'p2',
    lastUpdated: subtractDays(5),
    size: '156 KB',
    preview: 'Prepared by Client (PBC) list with 47 items. 32 complete, 10 in progress, 5 pending.',
    tags: ['audit', 'checklist'],
    linkedContacts: ['c2', 'c6'],
  },
  {
    id: 'd5',
    title: 'Revenue Recognition Memo',
    type: 'docx',
    folderId: 'f7',
    projectId: 'p2',
    lastUpdated: subtractDays(3),
    size: '89 KB',
    preview: 'Technical accounting memo on ASC 606 application for new SaaS contracts. Conclusion: recognize ratably over contract term.',
    tags: ['audit', 'technical', 'accounting'],
    linkedContacts: ['c2'],
  },
  {
    id: 'd6',
    title: '2026 Forecast Model',
    type: 'xlsx',
    folderId: 'f9',
    projectId: 'p3',
    lastUpdated: subtractDays(1),
    size: '4.7 MB',
    preview: '5-year financial model showing projected revenue CAGR of 15%, with covenant compliance through 2028.',
    tags: ['forecast', 'model', 'lender'],
    linkedContacts: ['c3', 'c7'],
  },
  {
    id: 'd7',
    title: 'Term Sheet - Capital One',
    type: 'pdf',
    folderId: 'f10',
    projectId: 'p3',
    lastUpdated: subtractDays(7),
    size: '234 KB',
    preview: 'Draft term sheet: $150M revolving facility, SOFR + 175bps, 5-year tenor. Key covenants: 3.5x leverage, 1.25x coverage.',
    tags: ['term sheet', 'lender', 'legal'],
    linkedContacts: ['c3', 'c8'],
  },
  {
    id: 'd8',
    title: 'Budget Template 2026',
    type: 'xlsx',
    folderId: 'f11',
    projectId: 'p4',
    lastUpdated: subtractDays(4),
    size: '1.2 MB',
    preview: 'Departmental budget templates with headcount planning and capital expenditure schedules.',
    tags: ['budget', 'planning'],
    linkedContacts: ['c5', 'c9'],
  },
  {
    id: 'd9',
    title: 'Cash Flow Projection',
    type: 'xlsx',
    folderId: 'f2',
    projectId: 'p1',
    lastUpdated: subtractDays(2),
    size: '890 KB',
    preview: '13-week cash flow forecast showing $45M available liquidity. No covenant concerns identified.',
    tags: ['cash', 'treasury', 'board'],
    linkedContacts: ['c7'],
  },
  {
    id: 'd10',
    title: 'Risk Register Update',
    type: 'xlsx',
    folderId: 'f3',
    projectId: 'p1',
    lastUpdated: subtractDays(1),
    size: '320 KB',
    preview: 'Enterprise risk register with 12 high-priority items. Cybersecurity and supply chain risks elevated.',
    tags: ['risk', 'board', 'compliance'],
    linkedContacts: ['c4'],
  },
];

// Messages (20+ across channels)
const me: Contact = {
  id: 'me',
  name: 'You',
  email: 'cfo@company.com',
  role: 'CFO',
  company: 'Acme Corp',
  isPriority: false,
};

export const messages: Message[] = [
  {
    id: 'm1',
    from: contacts[0],
    to: [me],
    subject: 'Board Meeting Agenda - Final Review Needed',
    preview: 'I\'d like to add a discussion on the M&A pipeline to the agenda...',
    body: 'Hi,\n\nI\'d like to add a discussion on the M&A pipeline to the agenda for next week\'s board meeting. Can you prepare a brief update on the three targets currently in due diligence?\n\nAlso, I noticed the cash flow projection hasn\'t been updated since last month. Please ensure this is current for the board pack.\n\nBest regards,\nSarah',
    channel: 'email',
    projectId: 'p1',
    priority: 'high',
    priorityReason: 'Sender is Board Chair, meeting in 3 days',
    timestamp: subtractHours(2),
    isRead: false,
    hasAttachments: false,
    threadId: 't1',
    suggestedReplies: [
      'I\'ll prepare the M&A update and have the revised materials to you by EOD tomorrow.',
      'The cash flow projection will be updated today. I\'ll include commentary on our liquidity position.',
    ],
  },
  {
    id: 'm2',
    from: contacts[1],
    to: [me],
    subject: 'Urgent: Revenue Recognition Testing',
    preview: 'We\'ve identified some questions regarding the Q3 contract modifications...',
    body: 'Good morning,\n\nDuring our testing of revenue recognition, we\'ve identified some questions regarding the Q3 contract modifications with TechCorp. Specifically:\n\n1. The modification appears to have been treated as a separate contract, but our initial assessment suggests it may need to be accounted for as part of the original agreement.\n\n2. We need supporting documentation for the standalone selling price determination.\n\nCan we schedule a call this afternoon to discuss? This is time-sensitive for our year-end close.\n\nRegards,\nMichael Torres\nKPMG',
    channel: 'email',
    projectId: 'p2',
    priority: 'high',
    priorityReason: 'Audit partner flagged as urgent, year-end close impact',
    timestamp: subtractHours(4),
    isRead: false,
    hasAttachments: true,
    threadId: 't2',
    suggestedReplies: [
      'Let\'s connect at 3pm today. I\'ll have Lisa pull the supporting documentation.',
      'I\'ll review the TechCorp contract modification and send you our analysis within 2 hours.',
    ],
  },
  {
    id: 'm3',
    from: contacts[2],
    to: [me],
    subject: 'Term Sheet Feedback',
    preview: 'The credit committee has reviewed the draft term sheet...',
    body: 'Hi,\n\nThe credit committee has reviewed the draft term sheet and we\'re close to final terms. A few points:\n\n1. We can move to SOFR + 150bps (from 175) based on your improved leverage profile\n2. The accordion feature has been approved at $50M\n3. We\'d like to tighten the leverage covenant to 3.25x (from 3.5x)\n\nCan you confirm these changes work for your planning assumptions? We\'d like to move to documentation by end of week.\n\nBest,\nDavid',
    channel: 'email',
    projectId: 'p3',
    priority: 'high',
    priorityReason: 'Lender key term changes, decision needed this week',
    timestamp: subtractHours(6),
    isRead: true,
    hasAttachments: true,
    threadId: 't3',
    suggestedReplies: [
      'The improved pricing is appreciated. I\'ll run the 3.25x covenant through our model and respond by tomorrow.',
      'Let me discuss the covenant change with the CEO and get back to you within 24 hours.',
    ],
  },
  {
    id: 'm4',
    from: contacts[3],
    to: [me],
    subject: 'Quick sync before board meeting?',
    preview: 'Want to make sure we\'re aligned on the narrative...',
    body: 'Hey,\n\nWant to make sure we\'re aligned on the narrative for the board meeting. Can we do a quick 15-minute prep call tomorrow morning?\n\nParticularly want to discuss:\n- How to frame the Q4 margin improvement\n- Messaging around the M&A targets\n- Any concerns from Sarah I should be aware of\n\nThanks,\nJennifer',
    channel: 'slack',
    projectId: 'p1',
    priority: 'high',
    priorityReason: 'CEO requesting alignment before board meeting',
    timestamp: subtractHours(8),
    isRead: true,
    hasAttachments: false,
    threadId: 't4',
    suggestedReplies: [
      '9am works for me. I\'ll prepare talking points for each topic.',
      'Let\'s do 8:30am - I\'ll send a brief prep doc tonight.',
    ],
  },
  {
    id: 'm5',
    from: contacts[4],
    to: [me],
    subject: 'Budget variance report ready',
    preview: 'The November variance analysis is complete...',
    body: 'Hi,\n\nThe November variance analysis is complete. Key highlights:\n\n- Revenue $2.1M favorable (new enterprise deals)\n- OpEx $800K unfavorable (consulting fees for SAP project)\n- Net favorable variance of $1.3M\n\nFull report attached. Let me know if you need anything adjusted before it goes to the board.\n\nRobert',
    channel: 'email',
    projectId: 'p4',
    priority: 'medium',
    priorityReason: 'Budget update for board materials',
    timestamp: subtractHours(12),
    isRead: true,
    hasAttachments: true,
    threadId: 't5',
  },
  {
    id: 'm6',
    from: contacts[5],
    to: [me],
    subject: 'PBC items - status update',
    preview: 'We\'ve completed 5 more items this week...',
    body: 'Good afternoon,\n\nWe\'ve completed 5 more PBC items this week:\n- Bank confirmations (all 4 received)\n- AR aging analysis\n- Inventory count reconciliation\n- Fixed asset additions schedule\n- Intercompany balance confirmations\n\nStill pending:\n- Legal letter (waiting on outside counsel)\n- Pension actuarial report (expected Friday)\n\nLet me know if KPMG has any questions.\n\nLisa',
    channel: 'email',
    projectId: 'p2',
    priority: 'medium',
    timestamp: subtractHours(24),
    isRead: true,
    hasAttachments: false,
    threadId: 't6',
  },
  {
    id: 'm7',
    from: contacts[6],
    to: [me],
    subject: 'Liquidity update',
    preview: 'Weekly cash position report attached...',
    body: 'Hi,\n\nWeekly cash position attached.\n\nCurrent available liquidity: $47.2M\n- Cash: $22.1M\n- Revolver availability: $25.1M\n\nNo concerns for the 13-week horizon. The large vendor payment next week is fully covered.\n\nJames',
    channel: 'email',
    priority: 'low',
    timestamp: subtractHours(28),
    isRead: true,
    hasAttachments: true,
    threadId: 't7',
  },
  {
    id: 'm8',
    from: contacts[7],
    to: [me],
    subject: 'Credit agreement review',
    preview: 'Attached redline of the credit agreement...',
    body: 'Good morning,\n\nAttached is our redline of the Capital One credit agreement. Key changes we\'re proposing:\n\n1. Expanded permitted acquisitions basket\n2. More flexibility in the restricted payments covenant\n3. Additional cure rights\n\nHappy to discuss on a call when convenient.\n\nEmily Brown\nSmith & Associates',
    channel: 'email',
    projectId: 'p3',
    priority: 'medium',
    priorityReason: 'Legal review of credit terms',
    timestamp: subtractHours(48),
    isRead: true,
    hasAttachments: true,
    threadId: 't8',
  },
  {
    id: 'm9',
    from: contacts[8],
    to: [me],
    subject: 'FP&A team capacity',
    preview: 'Quick question about budget season resourcing...',
    body: 'Hi,\n\nWith budget season approaching, I wanted to flag that we\'re stretched thin. Between the board pack, audit support, and now budget templates, the team is working significant overtime.\n\nCould we discuss:\n1. Prioritization of the three workstreams\n2. Possibility of temporary staff augmentation\n\nThanks,\nAlex',
    channel: 'teams',
    priority: 'medium',
    timestamp: subtractHours(72),
    isRead: true,
    hasAttachments: false,
    threadId: 't9',
  },
  {
    id: 'm10',
    from: contacts[9],
    to: [me],
    subject: 'Follow-up: Investment opportunity',
    preview: 'Great meeting last week. Wanted to share additional materials...',
    body: 'Hi,\n\nGreat meeting last week. As promised, I\'m sharing additional materials on the growth equity opportunity we discussed.\n\nKey points:\n- $50-75M investment size\n- Minority stake, no change of control\n- Growth capital for expansion\n- 5-7 year horizon\n\nWould love to schedule a follow-up with Jennifer when timing is right.\n\nBest,\nMaria',
    channel: 'email',
    priority: 'low',
    timestamp: subtractDays(3),
    isRead: true,
    hasAttachments: true,
    threadId: 't10',
  },
  // WhatsApp messages
  {
    id: 'm11',
    from: contacts[0],
    to: [me],
    subject: 'Board prep',
    preview: 'Quick question - is the CFO commentary section done?',
    body: 'Quick question - is the CFO commentary section done? Sarah',
    channel: 'whatsapp',
    projectId: 'p1',
    priority: 'high',
    priorityReason: 'Board Chair direct message',
    timestamp: subtractHours(1),
    isRead: false,
    hasAttachments: false,
    threadId: 't11',
  },
  {
    id: 'm12',
    from: contacts[3],
    to: [me],
    subject: 'Re: Board prep',
    preview: 'Btw the compensation committee wants 5 mins...',
    body: 'Btw the compensation committee wants 5 mins on the exec bonus accrual. Can you be ready for that?',
    channel: 'whatsapp',
    projectId: 'p1',
    priority: 'high',
    priorityReason: 'CEO, board meeting related',
    timestamp: subtractHours(3),
    isRead: true,
    hasAttachments: false,
    threadId: 't12',
  },
  // More email threads
  {
    id: 'm13',
    from: contacts[1],
    to: [me],
    subject: 'Management representation letter',
    preview: 'Draft rep letter attached for your review...',
    body: 'Hi,\n\nDraft management representation letter attached for your review. Please note the specific representations on:\n- Going concern\n- Subsequent events\n- Related party transactions\n\nWe\'ll need this signed before we can issue our report.\n\nMichael',
    channel: 'email',
    projectId: 'p2',
    priority: 'medium',
    timestamp: subtractDays(2),
    isRead: true,
    hasAttachments: true,
    threadId: 't13',
  },
  {
    id: 'm14',
    from: contacts[2],
    to: [me],
    subject: 'Covenant compliance certificate template',
    preview: 'Here\'s the template for the quarterly compliance certificate...',
    body: 'Hi,\n\nHere\'s the template for the quarterly compliance certificate you\'ll need to deliver. First one due 45 days after quarter end.\n\nLet me know if the format works for your team.\n\nDavid',
    channel: 'email',
    projectId: 'p3',
    priority: 'low',
    timestamp: subtractDays(4),
    isRead: true,
    hasAttachments: true,
    threadId: 't14',
  },
  {
    id: 'm15',
    from: contacts[4],
    to: [me],
    subject: 'Headcount planning assumptions',
    preview: 'Need your input on the 2026 headcount assumptions...',
    body: 'Hi,\n\nNeed your input on the 2026 headcount assumptions before we finalize the budget templates:\n\n1. Merit increase assumption: 3.5%?\n2. New hires: 15 net adds?\n3. Bonus pool: 100% of target?\n\nPlease confirm or suggest alternatives.\n\nRobert',
    channel: 'email',
    projectId: 'p4',
    priority: 'medium',
    timestamp: subtractDays(5),
    isRead: true,
    hasAttachments: false,
    threadId: 't15',
  },
  {
    id: 'm16',
    from: contacts[5],
    to: [me],
    subject: 'Inventory observation scheduling',
    preview: 'KPMG wants to schedule the year-end inventory observation...',
    body: 'Hi,\n\nKPMG wants to schedule the year-end inventory observation for December 31st at the main warehouse. They\'ll have 3 staff members.\n\nCan you confirm this works? I\'ll coordinate with operations.\n\nLisa',
    channel: 'email',
    projectId: 'p2',
    priority: 'low',
    timestamp: subtractDays(6),
    isRead: true,
    hasAttachments: false,
    threadId: 't16',
  },
  {
    id: 'm17',
    from: contacts[7],
    to: [me],
    subject: 'Board resolutions needed',
    preview: 'For the refinancing, we\'ll need board resolutions...',
    body: 'Hi,\n\nFor the refinancing, we\'ll need the following board resolutions:\n\n1. Authorization to enter into the credit agreement\n2. Designation of authorized signatories\n3. Approval of the security documents\n\nI can prepare drafts if you\'d like. Target timing?\n\nEmily',
    channel: 'email',
    projectId: 'p3',
    priority: 'medium',
    timestamp: subtractDays(7),
    isRead: true,
    hasAttachments: false,
    threadId: 't17',
  },
  {
    id: 'm18',
    from: contacts[0],
    to: [me],
    subject: 'Audit committee pre-meeting',
    preview: 'Let\'s schedule the audit committee pre-meeting...',
    body: 'Hi,\n\nLet\'s schedule the audit committee pre-meeting for next Tuesday at 4pm. I\'d like to cover:\n\n1. Audit status and any issues\n2. Internal control updates\n3. Related party disclosures\n\nPlease confirm availability.\n\nSarah',
    channel: 'email',
    projectId: 'p2',
    priority: 'high',
    priorityReason: 'Board Chair, audit committee meeting',
    timestamp: subtractDays(1),
    isRead: true,
    hasAttachments: false,
    threadId: 't18',
  },
  {
    id: 'm19',
    from: contacts[8],
    to: [me],
    subject: 'Model update complete',
    preview: 'The 5-year model has been updated with the new assumptions...',
    body: 'Hi,\n\nThe 5-year model has been updated with the new assumptions from Capital One:\n\n- SOFR + 150bps (down from 175)\n- 3.25x leverage covenant\n- $50M accordion\n\nGood news: We pass all covenants through the projection period with comfortable headroom.\n\nModel attached for your review.\n\nAlex',
    channel: 'email',
    projectId: 'p3',
    priority: 'medium',
    timestamp: subtractHours(5),
    isRead: true,
    hasAttachments: true,
    threadId: 't19',
  },
  {
    id: 'm20',
    from: contacts[6],
    to: [me],
    subject: 'FX hedging strategy',
    preview: 'Draft FX hedging policy attached for the board...',
    body: 'Hi,\n\nDraft FX hedging policy attached for board approval. Key points:\n\n- Hedge 75% of forecasted EUR exposures\n- 12-month rolling hedge program\n- Use of vanilla forwards only (no options)\n\nThis should address the board\'s concerns from last quarter.\n\nJames',
    channel: 'email',
    priority: 'low',
    timestamp: subtractDays(2),
    isRead: true,
    hasAttachments: true,
    threadId: 't20',
  },
  {
    id: 'm21',
    from: contacts[4],
    to: [me],
    subject: 'Confidential: Succession planning',
    preview: 'Need to discuss the FP&A director role...',
    body: 'Hi,\n\nConfidential - need to discuss the FP&A director role with you. Alex has indicated interest in external opportunities and I want to be prepared.\n\nCan we grab 30 minutes this week?\n\nRobert',
    channel: 'teams',
    priority: 'medium',
    timestamp: subtractHours(36),
    isRead: true,
    hasAttachments: false,
    threadId: 't21',
  },
];

// Calendar events (with conflicts)
export const calendarEvents: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Board Meeting Prep - CEO',
    description: 'Final alignment on board presentation',
    start: addHours(20),
    end: addHours(21),
    location: 'CEO Office',
    participants: [contacts[3]],
    projectId: 'p1',
  },
  {
    id: 'e2',
    title: 'Q4 Board Meeting',
    description: 'Quarterly board meeting',
    start: addDays(3),
    end: new Date(addDays(3).getTime() + 4 * 60 * 60 * 1000),
    location: 'Board Room',
    participants: [contacts[0], contacts[3], contacts[4]],
    projectId: 'p1',
    meetingId: 'meet1',
  },
  {
    id: 'e3',
    title: 'Audit Status Call - KPMG',
    description: 'Weekly audit progress review',
    start: addHours(4),
    end: addHours(5),
    location: 'Video Conference',
    participants: [contacts[1], contacts[5]],
    projectId: 'p2',
    meetingId: 'meet2',
  },
  {
    id: 'e4',
    title: 'Lender Call - Capital One',
    description: 'Term sheet negotiation',
    start: addHours(4),
    end: addHours(5),
    location: 'Phone',
    participants: [contacts[2], contacts[7]],
    projectId: 'p3',
    meetingId: 'meet3',
    isConflict: true,
    conflictWith: 'e3',
  },
  {
    id: 'e5',
    title: 'FP&A Team Meeting',
    description: 'Weekly team standup',
    start: addDays(1),
    end: new Date(addDays(1).getTime() + 1 * 60 * 60 * 1000),
    participants: [contacts[4], contacts[8]],
  },
  {
    id: 'e6',
    title: 'Audit Committee Pre-Meeting',
    description: 'Prep with Board Chair',
    start: addDays(2),
    end: new Date(addDays(2).getTime() + 1 * 60 * 60 * 1000),
    location: 'Board Room',
    participants: [contacts[0]],
    projectId: 'p2',
    meetingId: 'meet4',
  },
  {
    id: 'e7',
    title: 'Budget Kickoff',
    description: '2026 budget planning kickoff',
    start: addDays(5),
    end: new Date(addDays(5).getTime() + 2 * 60 * 60 * 1000),
    location: 'Conference Room A',
    participants: [contacts[4], contacts[5], contacts[8]],
    projectId: 'p4',
    meetingId: 'meet5',
  },
  {
    id: 'e8',
    title: 'Investor Meeting - Summit Capital',
    description: 'Follow-up on growth equity discussion',
    start: addDays(7),
    end: new Date(addDays(7).getTime() + 1.5 * 60 * 60 * 1000),
    location: 'External',
    participants: [contacts[9], contacts[3]],
  },
];

// Tasks
export const tasks: Task[] = [
  {
    id: 'task1',
    title: 'Finalize CFO commentary for board deck',
    description: 'Complete the CFO section of the board presentation',
    status: 'in_progress',
    priority: 'high',
    dueDate: addDays(1),
    projectId: 'p1',
    createdAt: subtractDays(7),
    sourceType: 'email',
    sourceId: 'm1',
  },
  {
    id: 'task2',
    title: 'Update cash flow projection',
    status: 'todo',
    priority: 'high',
    dueDate: addDays(1),
    projectId: 'p1',
    createdAt: subtractDays(2),
    sourceType: 'email',
    sourceId: 'm1',
  },
  {
    id: 'task3',
    title: 'Prepare M&A pipeline update',
    description: 'Brief update on 3 targets in due diligence',
    status: 'todo',
    priority: 'high',
    dueDate: addDays(2),
    projectId: 'p1',
    createdAt: subtractHours(2),
    sourceType: 'email',
    sourceId: 'm1',
  },
  {
    id: 'task4',
    title: 'Review TechCorp contract modification',
    description: 'Assess revenue recognition treatment',
    status: 'in_progress',
    priority: 'high',
    dueDate: today,
    projectId: 'p2',
    createdAt: subtractHours(4),
    sourceType: 'email',
    sourceId: 'm2',
  },
  {
    id: 'task5',
    title: 'Run covenant sensitivity analysis',
    description: 'Test 3.25x leverage covenant against projections',
    status: 'done',
    priority: 'high',
    dueDate: today,
    projectId: 'p3',
    createdAt: subtractHours(6),
    completedAt: subtractHours(1),
    sourceType: 'email',
    sourceId: 'm3',
  },
  {
    id: 'task6',
    title: 'Schedule CEO prep call',
    status: 'done',
    priority: 'medium',
    dueDate: today,
    projectId: 'p1',
    createdAt: subtractHours(8),
    completedAt: subtractHours(4),
    sourceType: 'email',
    sourceId: 'm4',
  },
  {
    id: 'task7',
    title: 'Review audit PBC list status',
    status: 'done',
    priority: 'medium',
    dueDate: subtractDays(1),
    projectId: 'p2',
    createdAt: subtractDays(3),
    completedAt: subtractDays(1),
  },
  {
    id: 'task8',
    title: 'Approve headcount planning assumptions',
    status: 'todo',
    priority: 'medium',
    dueDate: addDays(3),
    projectId: 'p4',
    createdAt: subtractDays(5),
    sourceType: 'email',
    sourceId: 'm15',
  },
  {
    id: 'task9',
    title: 'Review management representation letter',
    status: 'todo',
    priority: 'medium',
    dueDate: addDays(5),
    projectId: 'p2',
    createdAt: subtractDays(2),
    sourceType: 'email',
    sourceId: 'm13',
  },
  {
    id: 'task10',
    title: 'Prepare board resolutions for refinancing',
    status: 'todo',
    priority: 'medium',
    dueDate: addDays(7),
    projectId: 'p3',
    createdAt: subtractDays(7),
    sourceType: 'email',
    sourceId: 'm17',
  },
  {
    id: 'task11',
    title: 'Review legal redline on credit agreement',
    status: 'todo',
    priority: 'low',
    dueDate: addDays(4),
    projectId: 'p3',
    createdAt: subtractDays(2),
  },
  {
    id: 'task12',
    title: 'Review FX hedging policy for board',
    status: 'todo',
    priority: 'low',
    dueDate: addDays(2),
    projectId: 'p1',
    createdAt: subtractDays(2),
  },
  {
    id: 'task13',
    title: 'Follow up on pension actuarial report',
    status: 'in_progress',
    priority: 'medium',
    dueDate: addDays(2),
    projectId: 'p2',
    assignee: contacts[5],
    createdAt: subtractDays(1),
  },
  {
    id: 'task14',
    title: 'Discuss FP&A resourcing with Robert',
    status: 'todo',
    priority: 'medium',
    dueDate: addDays(3),
    projectId: 'p4',
    createdAt: subtractHours(72),
    sourceType: 'email',
    sourceId: 'm9',
  },
  {
    id: 'task15',
    title: 'Prepare exec bonus accrual summary',
    description: 'For compensation committee discussion',
    status: 'todo',
    priority: 'high',
    dueDate: addDays(2),
    projectId: 'p1',
    createdAt: subtractHours(3),
    sourceType: 'email',
    sourceId: 'm12',
  },
];

// Meetings
const sampleTranscript: TranscriptEntry[] = [
  { speaker: 'Michael Torres', text: 'Good morning everyone. Let\'s start with the audit status update.', timestamp: 0 },
  { speaker: 'You', text: 'Thanks Michael. We\'ve made good progress on the PBC list.', timestamp: 15 },
  { speaker: 'Lisa Anderson', text: 'Yes, we\'ve completed 37 of 47 items. The main outstanding items are the legal letter and pension report.', timestamp: 30 },
  { speaker: 'Michael Torres', text: 'That\'s good progress. I do want to flag the revenue recognition issue we discussed in my email.', timestamp: 50 },
  { speaker: 'You', text: 'Understood. We\'re reviewing the TechCorp modification now and will have analysis ready by end of day.', timestamp: 70 },
  { speaker: 'Michael Torres', text: 'Perfect. Let\'s also discuss the going concern analysis timeline.', timestamp: 90 },
];

const sampleMinutes: MeetingMinutes = {
  agenda: [
    'PBC list status review',
    'Revenue recognition discussion',
    'Going concern analysis timeline',
    'Year-end close schedule',
  ],
  discussion: [
    'PBC completion at 79% (37/47 items)',
    'TechCorp contract modification requires additional analysis',
    'Going concern memo drafting to begin next week',
    'Target completion date for fieldwork: December 20th',
  ],
  decisions: [
    'CFO to provide revenue recognition analysis by EOD',
    'Going concern memo to use 12-month look-forward period',
    'Weekly status calls to continue through year-end',
  ],
  risks: [
    'Legal letter pending - escalate with outside counsel',
    'Pension actuarial report timing uncertain',
  ],
  nextSteps: [
    'Complete revenue recognition analysis',
    'Follow up on legal letter',
    'Begin drafting going concern memo',
  ],
  isConfirmed: true,
};

const sampleFollowUps: FollowUpDraft[] = [
  {
    id: 'fu1',
    type: 'email',
    title: 'Audit Call Follow-up',
    content: 'Hi Michael,\n\nThank you for the productive call today. As discussed, I will have the TechCorp revenue recognition analysis to you by end of day.\n\nWe will also escalate the legal letter with outside counsel to ensure timely receipt.\n\nBest regards',
    recipient: contacts[1],
  },
  {
    id: 'fu2',
    type: 'message',
    title: 'Legal Letter Reminder',
    content: 'Hi Emily - following up on the audit legal letter. KPMG needs this by Dec 15. Can you confirm we\'re on track?',
    recipient: contacts[7],
  },
];

export const meetings: Meeting[] = [
  {
    id: 'meet1',
    title: 'Q4 Board Meeting',
    description: 'Quarterly board meeting',
    start: addDays(3),
    end: new Date(addDays(3).getTime() + 4 * 60 * 60 * 1000),
    participants: [contacts[0], contacts[3], contacts[4]],
    projectId: 'p1',
    status: 'upcoming',
  },
  {
    id: 'meet2',
    title: 'Audit Status Call - KPMG',
    description: 'Weekly audit progress review',
    start: addHours(4),
    end: addHours(5),
    participants: [contacts[1], contacts[5]],
    projectId: 'p2',
    status: 'upcoming',
  },
  {
    id: 'meet3',
    title: 'Lender Call - Capital One',
    description: 'Term sheet negotiation',
    start: addHours(4),
    end: addHours(5),
    participants: [contacts[2], contacts[7]],
    projectId: 'p3',
    status: 'upcoming',
  },
  {
    id: 'meet4',
    title: 'Audit Committee Pre-Meeting',
    description: 'Prep with Board Chair',
    start: addDays(2),
    end: new Date(addDays(2).getTime() + 1 * 60 * 60 * 1000),
    participants: [contacts[0]],
    projectId: 'p2',
    status: 'upcoming',
  },
  {
    id: 'meet5',
    title: 'Budget Kickoff',
    description: '2026 budget planning kickoff',
    start: addDays(5),
    end: new Date(addDays(5).getTime() + 2 * 60 * 60 * 1000),
    participants: [contacts[4], contacts[5], contacts[8]],
    projectId: 'p4',
    status: 'upcoming',
  },
  // Past meetings with outputs
  {
    id: 'meet6',
    title: 'Weekly Audit Sync',
    description: 'Previous week audit status',
    start: subtractDays(7),
    end: new Date(subtractDays(7).getTime() + 1 * 60 * 60 * 1000),
    participants: [contacts[1], contacts[5]],
    projectId: 'p2',
    status: 'completed',
    transcript: sampleTranscript,
    minutes: sampleMinutes,
    actionItems: [tasks[3], tasks[6]],
    followUpDrafts: sampleFollowUps,
  },
  {
    id: 'meet7',
    title: 'FP&A Monthly Review',
    description: 'Monthly finance review',
    start: subtractDays(14),
    end: new Date(subtractDays(14).getTime() + 1.5 * 60 * 60 * 1000),
    participants: [contacts[4], contacts[8]],
    projectId: 'p4',
    status: 'completed',
    transcript: [
      { speaker: 'Robert Kim', text: 'Let\'s review the November results and variance analysis.', timestamp: 0 },
      { speaker: 'Alex Thompson', text: 'Revenue came in $2.1M favorable due to the enterprise deals we closed.', timestamp: 15 },
      { speaker: 'You', text: 'Great work on the deal support. What\'s driving the OpEx variance?', timestamp: 30 },
      { speaker: 'Robert Kim', text: 'The SAP consulting fees hit higher than budgeted. We\'re $800K over.', timestamp: 45 },
    ],
    minutes: {
      agenda: ['November variance review', 'Q4 forecast update', 'Budget timeline'],
      discussion: ['Revenue favorable $2.1M', 'OpEx unfavorable $800K', 'Net favorable $1.3M'],
      decisions: ['Accelerate SAP project to reduce consulting spend', 'Maintain Q4 forecast'],
      risks: ['SAP project timeline at risk'],
      nextSteps: ['Prepare December close', 'Finalize budget templates'],
      isConfirmed: true,
    },
  },
  {
    id: 'meet8',
    title: 'Capital One Intro Call',
    description: 'Initial refinancing discussion',
    start: subtractDays(21),
    end: new Date(subtractDays(21).getTime() + 1 * 60 * 60 * 1000),
    participants: [contacts[2]],
    projectId: 'p3',
    status: 'completed',
  },
];

// Notifications
export const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'meeting_reminder',
    title: 'Audit Status Call in 15 minutes',
    message: 'Your call with KPMG starts at 2:00 PM',
    timestamp: subtractHours(0.25),
    isRead: false,
    actionUrl: '/meetings/meet2',
    contextBriefing: 'Key topics: Revenue recognition issue with TechCorp contract, PBC list status (37/47 complete). Michael flagged urgency on the ASC 606 analysis.',
  },
  {
    id: 'n2',
    type: 'critical_message',
    title: 'High Priority: Board Chair Message',
    message: 'Sarah Chen sent a message about Board Meeting Agenda',
    timestamp: subtractHours(2),
    isRead: false,
    actionUrl: '/messages/m1',
  },
  {
    id: 'n3',
    type: 'task_deadline',
    title: 'Task Due Today',
    message: 'Review TechCorp contract modification is due today',
    timestamp: subtractHours(8),
    isRead: true,
    actionUrl: '/tasks/task4',
  },
  {
    id: 'n4',
    type: 'task_completed',
    title: 'Task Completed',
    message: 'Covenant sensitivity analysis has been completed',
    timestamp: subtractHours(1),
    isRead: true,
  },
  {
    id: 'n5',
    type: 'daily_summary',
    title: 'Your Daily Briefing',
    message: '5 meetings today, 3 high priority tasks, 4 unread messages',
    timestamp: subtractHours(10),
    isRead: true,
  },
];

// AI Suggestions
export const suggestions: AIsuggestion[] = [
  {
    id: 's1',
    title: 'Resolve scheduling conflict',
    description: 'The Audit Status Call and Lender Call are scheduled at the same time. Suggest rescheduling the Lender Call.',
    action: 'Propose moving Lender Call to 3:00 PM',
    projectId: 'p3',
    meetingId: 'meet3',
  },
  {
    id: 's2',
    title: 'Prepare board brief',
    description: 'Based on Sarah\'s email, prepare a 1-page M&A pipeline summary for the board meeting.',
    action: 'Generate M&A brief draft',
    projectId: 'p1',
    messageId: 'm1',
    artifactType: 'draft',
  },
  {
    id: 's3',
    title: 'Reply to audit partner',
    description: 'Michael Torres is waiting for a response about the TechCorp revenue recognition issue.',
    action: 'Draft email confirming analysis timeline',
    projectId: 'p2',
    messageId: 'm2',
    artifactType: 'draft',
  },
];

// Connectors
export const connectors: Connector[] = [
  {
    id: 'conn1',
    name: 'Gmail',
    type: 'gmail',
    status: 'connected',
    lastSync: subtractHours(0.5),
    icon: '📧',
  },
  {
    id: 'conn2',
    name: 'Google Calendar',
    type: 'gmail',
    status: 'connected',
    lastSync: subtractHours(0.25),
    icon: '📅',
  },
  {
    id: 'conn3',
    name: 'Google Drive',
    type: 'gdrive',
    status: 'connected',
    lastSync: subtractHours(1),
    icon: '📁',
  },
  {
    id: 'conn4',
    name: 'Microsoft Teams',
    type: 'teams',
    status: 'connected',
    lastSync: subtractHours(0.5),
    icon: '💬',
  },
  {
    id: 'conn5',
    name: 'WhatsApp',
    type: 'whatsapp',
    status: 'connected',
    lastSync: subtractHours(0.1),
    icon: '📱',
  },
  {
    id: 'conn6',
    name: 'Slack',
    type: 'slack',
    status: 'disconnected',
    icon: '💼',
  },
];

// Avatars
export const avatars: Avatar[] = [
  { id: 'av1', name: 'Alex', imageUrl: '/avatars/alex.jpg' },
  { id: 'av2', name: 'Jordan', imageUrl: '/avatars/jordan.jpg' },
  { id: 'av3', name: 'Sam', imageUrl: '/avatars/sam.jpg' },
  { id: 'av4', name: 'Taylor', imageUrl: '/avatars/taylor.jpg' },
  { id: 'av5', name: 'Morgan', imageUrl: '/avatars/morgan.jpg' },
  { id: 'av6', name: 'Riley', imageUrl: '/avatars/riley.jpg' },
];

// Initial app state
export const initialAppState: AppState = {
  user: {
    name: 'Alex Morgan',
    email: 'cfo@acmecorp.com',
    role: 'Chief Financial Officer',
  },
  onboarding: {
    completed: false,
    currentStep: 0,
    selectedAvatarId: undefined,
    connectedSources: [],
    firstProjectId: undefined,
    priorityContactIds: [],
  },
  settings: {
    selectedAvatarId: 'av1',
    notificationPreferences: {
      desktop: true,
      mobile: true,
      dailySummary: true,
      meetingReminder15min: true,
      meetingReminder5min: true,
      criticalMessages: true,
    },
    connectors: connectors,
  },
  currentProjectId: null,
  contacts,
  messages,
  threads: [],
  calendar: calendarEvents,
  tasks,
  projects,
  documents,
  folders,
  meetings,
  notifications,
  suggestions,
  avatars,
};
